import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import me from '../../public/images/profile/me2.png'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import bg_video from '../../public/videos/production_id_3945140 (2160p).mp4'
import TransitionEffect from '@/components/TransitionEffect'
import { useRouter } from 'next/router';
import { MdOutlineArrowForwardIos } from 'react-icons/md';
import { MdOutlineArrowBackIos } from 'react-icons/md';
import { motion } from 'framer-motion';
import { FacebookOutlined, GithubOutlined, InstagramOutlined, YoutubeOutlined } from '@ant-design/icons';


export default function Home() {
  const router = useRouter();

  const handleArrowClickRight = () => {
    router.push('/about')
  }
  const handleArrowClickLeft = () => {
    router.push('/activity')
  }

  const socialMediaIconVariants = {
    hover: {
      scale: 1.2,
    },
  };
  return (
    <>
      <Head>
        <title>Norawit Creative</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className='flex items-center text-dark w-full  min-h-screen relative'>

        <Layout className='pt-0 '>
          <div
            className='flex items-center justify-between w-full gap-20 relative'
            style={{ zIndex: '1' }}
          >
            <div className='flex-col flex items-center w-1/3 h-auto pb-36'>
              <div className='pb-4 '>
                <Image src={me}
                  alt='MyImage'
                  className='w-40 h-40 rounded-full border-2 border-black'
                  style={{ objectFit: 'cover' }}
                />
                <div className='flex gap-2 justify-center pt-2'>
                  <Link href={'https://www.facebook.com/dew.zaa.35'}>
                    <motion.div whileHover="hover">
                      <FacebookOutlined style={{ fontSize: '24px', color: 'black' }} />
                    </motion.div>
                  </Link>
                  <Link href={'https://github.com/dewsiro000'}>
                    <motion.div whileHover="hover">
                      <GithubOutlined style={{ fontSize: '24px', color: 'black' }} />
                    </motion.div>
                  </Link>
                  <Link href={'https://www.instagram.com/dew_norr/'}>
                    <motion.div whileHover="hover">
                      <InstagramOutlined style={{ fontSize: '24px', color: 'black' }} />
                    </motion.div>
                  </Link>
                  <Link href={'https://www.facebook.com/dew.zaa.35'}>
                    <motion.div whileHover="hover">
                      <YoutubeOutlined style={{ fontSize: '24px', color: 'black' }} />
                    </motion.div>
                  </Link>
                </div>
              </div>
              <div className='flex-wrap border-2  border-black w-64 h-full bg-white p-4 '>
                <p>Name: Norawit Paha</p>
                <p>Age: 22</p>
                <p>sex: Male</p>
                <p>Religion : Buddhist</p>
              </div>
            </div>
            <div className='pr-60 w-full flex flex-col  items-center self-center'>
              <AnimatedText text="Hello" className='!text=6xl text-red-700' /><br></br>
              <AnimatedText text="I am Norawit Paha" className='!text=6xl' />
              <AnimatedText text="Frontend Developer" className='text-3xl text-green-700' />
              <p className='my-4 text-base font-medium bg-white p-2 bg-opacity-30'>
                As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications.
                Explore my latest projects and articles, showcasing my expertise in React and Nextjs I;m web development.
              </p>
              <div className='flex items-center self-start mt-2'>
                <Link href="/dummy.pdf" target='_blank'
                  className='flex items-center bg-dark text-light p-2.5 px-6
                  rounded-lg text-lg font-semibold hover:bg-light  hover:text-dark
                  border border-solid boder-transparent hover:border-dark
                  '
                  download={true}
                >Resume <LinkArrow className={"w-6 ml-1"} />

                </Link>
                <Link href="mailo:dewsiro000@gmail.com" target='_blank'
                  className='ml-4 text-lg fonr-medium capitalize text-dark underline'
                >Contact</Link>
              </div>
            </div>
          </div>
          <div className="absolute inset-0 z-0">
            <video
              autoPlay
              loop
              muted
              className="w-full h-full object-cover"
              style={{ position: 'absolute', zIndex: '-1' }}
            >
              <source src={bg_video} type="video/mp4" />
            </video>
          </div>
        </Layout>
        <motion.button
          onClick={handleArrowClickRight}
          whileHover={{ scale: 1.1 }}
          whileTap={{ scale: 0.9 }}
          className='bg-red-800 bg-opacity-0 w-20 h-20 absolute top-1/2 right-0 flex items-center justify-center'
        >
          <MdOutlineArrowForwardIos
            className="text-white"
            style={{ fontSize: '60px' }}
          />
        </motion.button>

        <motion.button
          onClick={handleArrowClickLeft}
          whileHover={{ scale: 1.1 }}
          whileTap={{ scale: 0.9 }}
          className='bg-red-800 bg-opacity-0 w-20 h-20 absolute top-1/2 left-0 flex items-center justify-center'
        >
          <MdOutlineArrowBackIos
            className="text-white"
            style={{ fontSize: '60px' }}
          />
        </motion.button>
        {/* <HireMe /> */}
        {/* <div className='absolute top-80 right-0 inline-block w-72'>
          <Image src={Codepic} alt="Codebucks" className='w-full h-auto' />
        </div> */}
      </main >
    </>
  )
}
